mod.id="footprintparticle"
mod.name="Footprint Particle"
mod.version="0.5.5"
mod.description="A simply mod that adds footprint for all mobs (and players)."
mod.author="Rimo"
mod.contributor="YOU"
mod.sources="https://github.com/Rivmun/FootprintParticle"
mod.issues="https://github.com/Rivmun/FootprintParticle/issues"
mod.homepage="https://www.curseforge.com/minecraft/mc-mods/footprintparticle"
mod.modrinth="https://modrinth.com/mod/footprintparticle"
mod.mcmod="https://www.mcmod.cn/class/9454.html"
mod.license="GPL-3.0-or-later"
mod.icon="icon.png"

["26.1-fabric"]
deps.minecraft="26.1.2"
version_range=">=26.1"
deps.fabric="0.19.2"
deps.fabric-api="0.146.1+26.1.2"
deps.modmenu="18.0.0"
deps.cloth="26.1.154"

["26.1-neoforge"]
loom.platform="neoforge"
deps.minecraft="26.1.2"
version_range="[26.1,)"
deps.neoforge="26.1.2.75"
neoforge_min_version="26.1"
deps.cloth="26.1.154"

["1.21.11-fabric"]
deps.minecraft="1.21.11"
version_range="=1.21.11"
deps.fabric="0.18.4"
deps.fabric-api="0.141.3+1.21.11"
deps.modmenu="17.0.0"
deps.cloth="21.11.153"

["1.21.11-neoforge"]
loom.platform="neoforge"
deps.minecraft="1.21.11"
version_range="[1.21.11]"
deps.neoforge="21.11.42"
neoforge_min_version="21.11"
deps.cloth="21.11.153"

["1.21.1-fabric"]
deps.minecraft="1.21.1"
version_range="=1.21.1"
deps.fabric="0.18.4"
deps.fabric-api="0.116.9+1.21.1"
deps.modmenu="11.0.1"
deps.cloth="15.0.140"

["1.21.1-neoforge"]
loom.platform="neoforge"
deps.minecraft="1.21.1"
version_range="[1.21.1]"
deps.neoforge="21.1.219"
neoforge_min_version="21.1"
deps.cloth="15.0.140"
