mod.id="footprintparticle"
mod.name="Footprint Particle"
mod.version="0.5.4"
mod.description="A simply mod that adds footprint for all mobs (and players)."
mod.author="Rimo"
mod.contributor="YOU"
mod.sources="https://github.com/Rivmun/FootprintParticle"
mod.issues="https://github.com/Rivmun/FootprintParticle/issues"
mod.homepage="https://www.curseforge.com/minecraft/mc-mods/footprintparticle"
mod.modrinth="https://modrinth.com/mod/footprintparticle"
mod.mcmod="https://www.mcmod.cn/class/9454.html"
mod.license="GPL-3.0-or-later"
mod.icon="icon.png"

["26.1-fabric"]
deps.minecraft="26.1.2"
version_range=">=26.1"
deps.fabric="0.19.2"
deps.fabric-api="0.146.1+26.1.2"
deps.modmenu="18.0.0"
deps.cloth="26.1.154"

["26.1-neoforge"]
loom.platform="neoforge"
deps.minecraft="26.1.2"
version_range="[26.1,)"
deps.neoforge="26.1.2.75"
neoforge_min_version="26.1"
deps.cloth="26.1.154"
